// Course data transcribed directly from the Ministry of Labor and Skills
// curriculum PDFs uploaded for each TVET program. Keys are "Department|Level".

export const TVET_COURSES = {
  "Nursing|Level 3": [
    ["HLT NUR3 01 1221", "Provide Motivated, Competent, and Compassionate Caring Service"],
    ["HLT NUR3 02 1221", "Apply Infection Prevention Techniques and Workplace OHS"],
    ["HLT NUR3 03 1221", "Provide Basic First Aid and Emergency Response"],
    ["HLT NUR3 04 1221", "Prepare and Maintain Beds"],
    ["HLT NUR3 05 1221", "Provide Basic Nursing Care"],
    ["HLT NUR3 06 1221", "Provide Wound Care"],
    ["HLT NUR3 07 1221", "Administer and Monitor Range of Medication"],
    ["HLT NUR3 08 1221", "Provide Palliative Care and Maintain Mortuary Service"],
    ["HLT NUR3 09 1221", "Provide Comprehensive Family Planning Service"],
    ["HLT NUR3 10 1121", "Provide Youth, Adolescent and Reproductive Health Service"],
    ["HLT NUR3 11 1121", "Perform Community Mobilization and Health Education"],
    ["HLT NUR3 12 1121", "Apply Computer and Mobile Technology"],
    ["HLT NUR3 13 1121", "Apply Basic Health Statistics and Survey"],
    ["HLT NUR3 14 1121", "Apply 5S Procedure"],
  ],
  "Nursing|Level 4": [
    ["HLT NUR4-M1", "Advanced Nursing Care"],
    ["HLT NUR4-M2", "Nursing Assessment"],
    ["HLT NUR4-M3", "Communicable and Neglected Tropical Diseases"],
    ["HLT NUR4-M4", "Medical - Surgical Nursing"],
    ["HLT NUR4-M5", "Non-communicable Diseases"],
    ["HLT NUR4-M6", "Pre, Intra and Post-Operative Nursing"],
    ["HLT NUR4-M7", "Maternal Health Care"],
    ["HLT NUR4-M8", "Child Health Care"],
    ["HLT NUR4-M9", "Nutrition and Dietary Service"],
    ["HLT NUR4-M10", "Mental Health Care"],
    ["HLT NUR4-M11", "Community Health Nursing"],
    ["HLT NUR4-M12", "Community Health Service Management"],
    ["HLT NUR4-M13", "MUDA (Prevent and Eliminate MUDA)"],
  ],
  "Medical Laboratory|Level 3": [
    ["HLT MLT3 01 1224", "Provide Motivated Competent and Compassionate Service"],
    ["HLT MLT3 02 1224", "Apply Infection Prevention Techniques and Workplace OHS"],
    ["HLT MLT3 03 1224", "Provide First Aid and Emergency Response"],
    ["HLT MLT3 04 1224", "Collect and Process Medical Samples"],
    ["HLT MLT3 05 1224", "Perform Equipment Handling and Maintenance"],
    ["HLT MLT3 06 1224", "Prepare Laboratory Solutions"],
    ["HLT MLT3 07 1224", "Perform Parasitological Examination"],
    ["HLT MLT3 08 1224", "Perform Urine and Body Fluid Analysis"],
    ["HLT MLT3 09 1224", "Apply Computer and Mobile Health Technology"],
    ["HLT MLT3 10 1224", "Apply Basic Health Statistics and Health Survey"],
    ["HLT MLT3 11 1224", "Perform Community Mobilization and Provide Health Education"],
    ["HLT MLT3 12 1224", "Apply 5S Procedures"],
  ],
  "Medical Laboratory|Level 4": [
    ["HLT MLT4 01 1121", "Use Info-technology Devices in the Workplace"],
    ["HLT MLT4 02 1121", "Perform Microbiological Tests"],
    ["HLT MLT4 03 1121", "Perform Hematological Tests"],
    ["HLT MLT4 04 1121", "Perform Serological Tests"],
    ["HLT MLT4 05 1121", "Perform Immuno-Haematological Tests"],
    ["HLT MLT4 06 1121", "Perform Clinical Chemistry Tests"],
    ["HLT MLT4 07 1121", "Prepare Histopathological Samples for Examination"],
    ["HLT MLT4 08 1121", "Implement Laboratory Quality Assurance"],
    ["HLT MLT4 09 1121", "Manage Community Health Service"],
    ["HLT MLT4 10 1121", "Prevent and Eliminate MUDA"],
  ],
  "Midwifery|Level 3": [
    ["HLT MDW3 01 0721", "Provide Motivated Competent and Compassionate Service"],
    ["HLT MDW3 02 0721", "Apply Computer and Mobile Health Technology"],
    ["HLT MDW3 03 0721", "Apply Infection Prevention Techniques and Workplace OHS"],
    ["HLT MDW3 04 0721", "Perform Community Mobilization and Provide Health Education"],
    ["HLT MDW3 05 0721", "Provide First Aid and Emergency Response"],
    ["HLT MDW3 06 0721", "Provide Adolescent, Youth and Reproductive Health Service"],
    ["HLT MDW3 07 0721", "Provide Range of Medication Relating Midwifery Practice"],
    ["HLT MDW3 08 0721", "Promote and Provide Immunization and Manage Cold Chain"],
    ["HLT MDW3 09 0721", "Manage Maternal Nutritional Problems and Provide Preconception Care"],
    ["HLT MDW3 10 0721", "Provide Common Medical and Surgical Care in Maternal Health Service"],
    ["HLT MDW3 11 0721", "Apply Basic Health Statistics and Survey"],
    ["HLT MDW3 12 0721", "Apply 5S Procedures"],
  ],
  "Midwifery|Level 4": [
    ["HLT MDW4 01 0721", "Promote and Provide Family Planning Service"],
    ["HLT MDW4 02 0721", "Provide and Manage Care during Pregnancy"],
    ["HLT MDW4 03 0721", "Provide and Manage Care during Labor and Birth"],
    ["HLT MDW4 04 0721", "Provide and Manage Postpartum Care for Mother and Neonate"],
    ["HLT MDW4 05 0721", "Provide and Manage Care for Newborn & Children"],
    ["HLT MDW4 06 0721", "Provide and Manage Care for Clients with Gynecological Problems"],
    ["HLT MDW4 07 0721", "Manage Community Health Service"],
    ["HLT MDW4 08 0721", "Prevent and Eliminate MUDA using Problem Solving Tools"],
  ],
  // Accounting Level 2 content is shared by both the Terminal and Diploma
  // paths — both go through the same Level 2 training before splitting.
  "Accounting|Level 2 Terminal": [
    ["LSA ACF2 01 1221", "Use Business Technology and Equipment"],
    ["LSA ACF2 02 1221", "Process Customer Accounts and Transactions"],
    ["LSA ACF2 03 1221", "Develop Understanding of the Ethiopian Financial System and Markets"],
    ["LSA ACF2 04 1221", "Develop Understanding of Taxation"],
    ["LSA ACF2 05 1221", "Prepare and Use a Personal Budget and Savings Plan"],
    ["LSA ACF2 06 1221", "Develop Understanding of Debt and Consumer Credit"],
    ["LSA ACF2 07 1221", "Apply Business Communication in the Work Place"],
    ["LSA ACF2 08 1221", "Produce, Record & Maintain Business Documents"],
    ["LSA ACF2 09 1221", "Apply 5S Procedures"],
  ],
  "Accounting|Level 3": [
    ["LSA ACF3 01 1221", "Process Financial Transactions and Extract Interim Reports"],
    ["LSA ACF3 02 1221", "Administer, Monitor and Control General and Subsidiary Ledgers"],
    ["LSA ACF3 03 1221", "Perform Financial Calculations"],
    ["LSA ACF3 04 1221", "Administer Financial Accounts"],
    ["LSA ACF3 05 1221", "Prepare, Match and Process Receipts"],
    ["LSA ACF3 06 1221", "Process Payment Documentation"],
    ["LSA ACF3 07 1221", "Balance Cash Holdings"],
    ["LSA ACF3 08 1221", "Process Payroll"],
    ["LSA ACF3 09 1221", "Prepare Financial Reports"],
    ["LSA ACF3 10 1221", "Calculate and Administer Taxes, Fees and Charges"],
    ["LSA ACF3 11 1221", "Handle Foreign Currency Transactions"],
    ["LSA ACF3 12 1221", "Prevent and Eliminate MUDA"],
  ],
  "Accounting|Level 4": [
    ["LSA ACF4 01 1221", "Prepare Financial Statements for Governmental and Not-for-Profit Entities (NFP)"],
    ["LSA ACF4 02 1221", "Set Up and Operate a Computerized Accounting Information System"],
    ["LSA ACF4 03 1221", "Apply Principles of Professional Practice to Work in the Financial Services Industry"],
    ["LSA ACF4 04 1221", "Prepare Financial Reports Based on International Financial Report Standard (IFRS)"],
    ["LSA ACF4 05 1221", "Process Business Tax Requirements"],
    ["LSA ACF4 06 1221", "Develop and Use Complex Spreadsheets"],
    ["LSA ACF4 07 1221", "Produce Job Order and Process Costing System"],
    ["LSA ACF4 08 1221", "Maintain Inventory Records and Valuation System"],
    ["LSA ACF4 09 1221", "Establish and Maintain a Cash and Accrual Accounting System"],
    ["LSA ACF4 10 1221", "Manage Overdue Customer Accounts"],
    ["LSA ACF4 11 1221", "Provide Management Accounting Information"],
    ["LSA ACF4 12 1221", "Perform Auditing and Reporting"],
  ],
  "HRM|Level 2 Terminal": [
    ["LSA HRM2 01 1221", "Prepare and Implement Human Resource Operational Plan"],
    ["LSA HRM2 02 1221", "Perform Human Resource Activities"],
    ["LSA HRM2 03 1221", "Organize Office Records"],
    ["LSA HRM2 04 1221", "Develop Employee Participation"],
    ["LSA HRM2 05 1221", "Deliver and Sustain Service to Customer"],
    ["LSA HRM2 06 1221", "Apply Human Resource Communication Skill"],
    ["LSA HRM2 07 1221", "Utilize and Maintain Organizational Information"],
    ["LSA HRM2 08 1221", "Participate in a Team"],
    ["LSA HRM2 09 1221", "Apply 5S Procedures"],
  ],
  "HRM|Level 3": [
    ["LSA HRM3 01 1221", "Perform Human Resource Function"],
    ["LSA HRM3 02 1221", "Apply Human Resource Management Rules & Regulations"],
    ["LSA HRM3 03 1221", "Ensure Employee Health and Safety"],
    ["LSA HRM3 04 1221", "Plan Human Resource"],
    ["LSA HRM3 05 1221", "Manage Recruitment, Selection, Induction and Promotion"],
    ["LSA HRM3 06 1221", "Implement Industrial Relations"],
    ["LSA HRM3 07 1221", "Manage Workforce Diversity"],
    ["LSA HRM3 08 1221", "Prevent and Eliminate MUDA"],
  ],
  "HRM|Level 4": [
    ["LSA HRM4 01 1221", "Administer Remuneration and Employee Benefits"],
    ["LSA HRM4 02 1221", "Manage Performance Management Systems"],
    ["LSA HRM4 03 1221", "Administer Human Resource Training and Development Programs"],
    ["LSA HRM4 04 1221", "Implement Human Resources Management System"],
    ["LSA HRM4 05 1221", "Handle Dispute Management Processes"],
    ["LSA HRM4 06 1221", "Lead Employees Movement and Separation"],
  ],
};

// Level 2 Diploma shares the exact same Level 2 course set as Level 2 Terminal
// (same training, the split is which path the student continues on afterward).
TVET_COURSES["Accounting|Level 2 Diploma"] = TVET_COURSES["Accounting|Level 2 Terminal"];
TVET_COURSES["HRM|Level 2 Diploma"] = TVET_COURSES["HRM|Level 2 Terminal"];
